language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y libhdf5-mpich-dev libhdf5-mpich-1.8.4
  - sudo apt-get install -y libfftw3-dev libnetcdf-dev
  - sudo apt-get install -y python-numpy python-netcdf python-scipy
  - sudo apt-get install -y python-matplotlib
script:
  - ./configure && make && ./.travis_script.sh
