sudo: required
dist: trusty
language: cpp
compiler: gcc
matrix:
  include:
  - env: CONFIGURE_OPTIONS='--enable-openmp'
  - env: CONFIGURE_OPTIONS='--enable-debug'
  allow_failures:
  - env: CONFIGURE_OPTIONS='' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
  - env: CONFIGURE_OPTIONS='--enable-openmp' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
  - env: CONFIGURE_OPTIONS='--enable-debug' MPICH_CC=clang MPICH_CXX=clang++
    compiler: clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y libfftw3-dev libnetcdf-dev
  - sudo apt-get install -y python-numpy python-netcdf python-scipy
  - sudo apt-get install -y python-matplotlib
script:
  - ./.travis_script.sh
