language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y libfftw3-dev libnetcdf-dev
script:
  - ./configure && make && ./examples/test_suite_make && ./examples/test_suite
